apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  serviceName: database-service
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: database:latest
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: "/data/db"
              name: database-pvc
  volumeClaimTemplates:
    - metadata:
        name: database-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
  selector:
    matchLabels:
      app: database