"""init_database

Revision ID: a0ef1fd58a15
Revises: 
Create Date: 2024-07-19 14:29:45.060921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0ef1fd58a15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('NEW', 'INSTALLING', 'RUNNING', native_enum=False), nullable=False),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("version ~ '^\\d+\\.\\d+\\.\\d+$'", name='version_format_check'),
    sa.CheckConstraint('char_length(description) <= 4096', name='description_length_check'),
    sa.CheckConstraint('char_length(kind) <= 32', name='kind_length_check'),
    sa.CheckConstraint('char_length(name) <= 128', name='name_length_check'),
    sa.PrimaryKeyConstraint('app_id')
    )
    op.create_index(op.f('ix_apps_app_id'), 'apps', ['app_id'], unique=True)
    op.create_index(op.f('ix_apps_kind'), 'apps', ['kind'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apps_kind'), table_name='apps')
    op.drop_index(op.f('ix_apps_app_id'), table_name='apps')
    op.drop_table('apps')
    # ### end Alembic commands ###
